apiVersion: v1
kind: Service
metadata:
  name: spring
spec:
  selector:
    app: spring
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-dl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring
  template:
    metadata:
      labels:
        app: spring
    spec:
      containers:
        - image: spring-boot-demo:v0.0.1
          name: react
          ports:
            - containerPort: 8080


